### ISSUE TITLE
prepSpecies and authorship names with 'et al.'

### ISSUE THREAD

**Issue by ggrittz** [LimaRAF/plantR#116]
Hi. I found a minor issue with how `plantR::prepSpecies` handles authorship names that contain et al.

Case below:
```
plantR::prepSpecies(x = data.frame(scientificName.new = "Brasiliorchis picta", 
                                                         scientificNameAuthorship.new = "(Hook.) R.B.Singer et al."))
```

Returns:
```
scientificName.new scientificNameAuthorship.new      family suggestedName suggestedAuthorship taxon.rank        tax.notes   id scientificNameFull
1 Brasiliorchis picta    (Hook.) R.B.Singer et al. Orchidaceae          <NA>                <NA>       <NA> replaced synonym <NA>               <NA>
```

Cheers!

**Comment by LimaRAF** [comment]
Hi @ggrittz 

Thanks for pointing this out. This issue is due to 'et al.' end in the authorships, but to the fact that the backbone point the name as a synonym that has no accepted id. So the replacement was being done but with NAs throughout.

Anyways, I added a if check to flag those cases and avoid the replacement by NA, creating a new category in the notes called 'synonym not replaced'. I have not tested this flag with a larger number of names and cases, but it should work out fine now. 

Please let me know if you find any other problems of this sort.

Cheers!
