### ISSUE TITLE
error rgbif2

### ISSUE THREAD

**Issue by gdauby** [LimaRAF/plantR#61]
I have an error running the example from the tutorial:
```

library("plantR")
spp <- c("Casearia sylvestris",
         "Euterpe edulis",
         "Trema micrantha")

occs_gbif <- rgbif2(species =  spp,
                    basisOfRecord = "PRESERVED_SPECIMEN",
                    remove_na = FALSE, limit = 500000)
```

This gives me an error

```
Making request to GBIF...
Making request to GBIF...
Making request to GBIF...
Error in names(gbif_data) <- species : 
  attribut 'names' [3] must be of same length than vector [2]
```

I run under:
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

**Comment by LimaRAF** [comment]
Dear @gdauby,

We recently (days ago) updated the function rgbif2() to have its own argument (i.e. `n.records`) to set the limit number of records to be downloaded. For our purposes, using the default from rgbif::occ_search() of 500 records (argument `limit`) was too low. But we forgot to update the tutorial.

The same chunck of the tutorial should now be: 
```
occs_gbif <- rgbif2(species =  spp,
                    basisOfRecord = "PRESERVED_SPECIMEN",
                    remove_na = FALSE, n.records = 500000)
```
This should take a while because two of the species have large number of records. But it should work out fine.  You may need to re-install the plantR from the master branch if you cannot find the argument `n.records` in rgbif2() in your intalled version of plantR.

Sorry for our mistake.

Cheers!

**Comment by LimaRAF** [comment]
@gdauby If you still have an issues please let me know. Closing this issue for now
