### ISSUE TITLE
rspecieslink does not returns field typeStatus

### ISSUE THREAD

**Issue by LimaRAF** [LimaRAF/plantR#9]
@saramortara

Not sure why the function rspecieslink is not returnig the filed typeStatus, which contain the info on type specimens and is key for taxonomical validation of the specimens. I know speciesLink provided this info but it is not in the data object of the function. I tried to set the argument Typus = TRUE but then the function reported an error ("Output is empty. Check your request.").

Any ideas on how to fix it?

Abs!

**Comment by jaum20** [comment]
I am currently facing this problem for some species. Using your example (Trema micrantha), the function does return the typeStatus  column, but for Enterolobium contortisiliquum, for instance, it doesn't returns the field´. Maybe this is because there is not type specimen for this species in the splink database
